[2022-05-03 20:56:59,519] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_2 2022-05-03T20:56:58.484563+00:00 [queued]>
[2022-05-03 20:56:59,551] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_2 2022-05-03T20:56:58.484563+00:00 [queued]>
[2022-05-03 20:56:59,551] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-05-03 20:56:59,551] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-05-03 20:56:59,552] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-05-03 20:56:59,562] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2022-05-03T20:56:58.484563+00:00
[2022-05-03 20:56:59,564] {standard_task_runner.py:52} INFO - Started process 144130 to run task
[2022-05-03 20:56:59,569] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_rule', 'task_2', '2022-05-03T20:56:58.484563+00:00', '--job-id', '119', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule.py', '--cfg-path', '/tmp/tmp_d5k7mz4', '--error-file', '/tmp/tmpw23o09d7']
[2022-05-03 20:56:59,576] {standard_task_runner.py:77} INFO - Job 119: Subtask task_2
[2022-05-03 20:56:59,694] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_rule.task_2 2022-05-03T20:56:58.484563+00:00 [running]> on host airflowvm
[2022-05-03 20:56:59,886] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-05-03T20:56:58.484563+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-03T20:56:58.484563+00:00
[2022-05-03 20:56:59,886] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-05-03 20:56:59,887] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'exit 1']
[2022-05-03 20:56:59,900] {subprocess.py:75} INFO - Output:
[2022-05-03 20:56:59,905] {subprocess.py:83} INFO - Command exited with return code 1
[2022-05-03 20:56:59,918] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-05-03 20:56:59,920] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=trigger_rule, task_id=task_2, execution_date=20220503T205658, start_date=20220503T205659, end_date=20220503T205659
[2022-05-03 20:56:59,972] {local_task_job.py:151} INFO - Task exited with return code 1
