[2022-04-28 13:07:34,334] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_process.is_api_available 2022-04-27T00:00:00+00:00 [queued]>
[2022-04-28 13:07:34,337] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_process.is_api_available 2022-04-27T00:00:00+00:00 [queued]>
[2022-04-28 13:07:34,337] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 13:07:34,337] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-04-28 13:07:34,337] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 13:07:34,343] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-04-27T00:00:00+00:00
[2022-04-28 13:07:34,344] {standard_task_runner.py:52} INFO - Started process 179632 to run task
[2022-04-28 13:07:34,348] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_process', 'is_api_available', '2022-04-27T00:00:00+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_process.py', '--cfg-path', '/tmp/tmpsmgq7yog', '--error-file', '/tmp/tmp47bevj_8']
[2022-04-28 13:07:34,349] {standard_task_runner.py:77} INFO - Job 34: Subtask is_api_available
[2022-04-28 13:07:34,375] {logging_mixin.py:104} INFO - Running <TaskInstance: user_process.is_api_available 2022-04-27T00:00:00+00:00 [running]> on host airflowvm
[2022-04-28 13:07:34,404] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_process
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-04-27T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-27T00:00:00+00:00
[2022-04-28 13:07:34,404] {http.py:101} INFO - Poking: api/
[2022-04-28 13:07:34,406] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2022-04-28 13:07:34,407] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-04-28 13:07:35,116] {base.py:243} INFO - Success criteria met. Exiting.
[2022-04-28 13:07:35,121] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_process, task_id=is_api_available, execution_date=20220427T000000, start_date=20220428T130734, end_date=20220428T130735
[2022-04-28 13:07:35,160] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-28 13:07:35,176] {local_task_job.py:151} INFO - Task exited with return code 0
