[2022-04-28 13:05:45,530] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_process.create_table 2022-04-27T00:00:00+00:00 [queued]>
[2022-04-28 13:05:45,533] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_process.create_table 2022-04-27T00:00:00+00:00 [queued]>
[2022-04-28 13:05:45,533] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 13:05:45,533] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2022-04-28 13:05:45,533] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 13:05:45,540] {taskinstance.py:1087} INFO - Executing <Task(SqliteOperator): create_table> on 2022-04-27T00:00:00+00:00
[2022-04-28 13:05:45,541] {standard_task_runner.py:52} INFO - Started process 178806 to run task
[2022-04-28 13:05:45,546] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_process', 'create_table', '2022-04-27T00:00:00+00:00', '--job-id', '31', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_process.py', '--cfg-path', '/tmp/tmpbfwqrckj', '--error-file', '/tmp/tmplz_72d0_']
[2022-04-28 13:05:45,546] {standard_task_runner.py:77} INFO - Job 31: Subtask create_table
[2022-04-28 13:05:45,576] {logging_mixin.py:104} INFO - Running <TaskInstance: user_process.create_table 2022-04-27T00:00:00+00:00 [running]> on host airflowvm
[2022-04-28 13:05:45,610] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_process
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-04-27T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-27T00:00:00+00:00
[2022-04-28 13:05:45,611] {sqlite.py:63} INFO - Executing: 
            CREATE TABLE IF NOT EXIST user(
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
                );
                
[2022-04-28 13:05:45,613] {base.py:69} INFO - Using connection to: id: db_sqlite. Host: /home/airflow/airflow/airflow.db, Port: None, Schema: , Login: , Password: None, extra: {}
[2022-04-28 13:05:45,613] {dbapi.py:204} INFO - Running statement: 
            CREATE TABLE IF NOT EXIST user(
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
                );
                , parameters: []
[2022-04-28 13:05:45,613] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/providers/sqlite/operators/sqlite.py", line 65, in execute
    hook.run(self.sql, parameters=self.parameters)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: near "EXIST": syntax error
[2022-04-28 13:05:45,614] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=user_process, task_id=create_table, execution_date=20220427T000000, start_date=20220428T130545, end_date=20220428T130545
[2022-04-28 13:05:45,663] {local_task_job.py:151} INFO - Task exited with return code 1
